### ISSUE TITLE
Error when disable sorting for column

### ISSUE THREAD

**Issue by wzywno** [rweng/jquery-datatables-rails#176]
There is an error when I disable sorting for column.

I want to disable sorting for two columns
In javascript I pass configuration to disable sorting for columns with class no-sort
```
$('.table').dataTable({
...
"aoColumnDefs" : [ {
            "orderable" : false,
            "aTargets" : [ "no-sort" ]
        },
```
in datatable class:
```
  def sortable_columns
    @sortable_columns ||= ['Artist.name', 'ArtObject.title', 'ArtCollection.title', 'ArtObject.status']
  end
```

As a result:
```
/gems/ajax-datatables-rails-0.3.0/lib/ajax-datatables-rails/base.rb:169:in `sort_column': [DEPRECATED] Using table_name.column_name notation is deprecated. Please refer to: https://github.com/antillas21/ajax-datatables-rails#searchable-and-sortable-columns-syntax
Completed 500 Internal Server Error in 24ms

TypeError - no implicit conversion from nil to integer:
  ajax-datatables-rails (0.3.0) lib/ajax-datatables-rails/base.rb:176:in `deprecated_sort_column'
  ajax-datatables-rails (0.3.0) lib/ajax-datatables-rails/base.rb:172:in `rescue in sort_column'
  ajax-datatables-rails (0.3.0) lib/ajax-datatables-rails/base.rb:169:in `sort_column'
  ajax-datatables-rails (0.3.0) lib/ajax-datatables-rails/base.rb:77:in `block in sort_records'
  ajax-datatables-rails (0.3.0) lib/ajax-datatables-rails/base.rb:76:in `sort_records'
  ajax-datatables-rails (0.3.0) lib/ajax-datatables-rails/base.rb:68:in `fetch_records'
  ajax-datatables-rails (0.3.0) lib/ajax-datatables-rails/base.rb:63:in `records'
```

Is there a way to disable sorting?

**Comment by ricardodovalle** [comment]
I did this way to disable column sort

````coffeescript
jQuery ->
  $('#people_table').DataTable
    columnDefs: [ { orderable: false, targets: [1,2,3] } ]
````
https://datatables.net/reference/option/columnDefs

**Comment by wzywno** [comment]
The problem was that in parameters sent to server there was 'orderable'  param with value set to 0, which means that data should be ordered by first column. And I disabled sorting by first column.

I fixed problem by adding  to configuration 
```
"aaSorting": []
```
which disables default ordering.
